version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-crud-dev
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pgcruddb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: